version: "3.8"

services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    volumes:
      - ./back/sql:/docker-entrypoint-initdb.d
    ports:
      - 3306:3306
    hostname: db
    stdin_open: true

  back:
    build:
      context: ./back
    environment:
      - FRONT_HOST=http://localhost:3000
      - DB_HOST=db
    volumes:
      - ./back:/back
    ports:
      - 8080:8080
    stdin_open: true

  front:
    build:
      context: ./front
    volumes:
      - ./front:/usr/src/app
    command: sh -c "yarn dev"
    ports:
      - 3000:3000
    stdin_open: true