version: "3.8"

services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    volumes:
      - ./back/sql:/docker-entrypoint-initdb.d
    ports:
      - 3306:3306
    hostname: db

  back:
    build:
      context: ./back
    volumes:
      - ./back:/back
    ports:
      - 8080:8080